name: 'data-engineering-project'
version: '1.0.0'
config-version: 2

profile: 'data_engineering_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  data-engineering-project:
    # Silver layer models
    silver:
      +materialized: table
      +partition_by:
        field: processing_timestamp
        data_type: timestamp
        granularity: day
    
    # Gold layer models  
    gold:
      +materialized: table
      +partition_by:
        field: processing_timestamp
        data_type: timestamp
        granularity: day 