data_engineering_project:
  target: dev
  outputs:
    dev:
      type: spark
      method: odbc
      driver: 'Simba Spark ODBC Driver'
      host: localhost
      port: 10000
      database: default
      schema: gold
      threads: 4
      # For Delta Lake tables
      table_type: delta
      # S3 configuration
      s3_bucket: your-data-bucket
      s3_region: us-east-1
      # Authentication (if needed)
      # aws_access_key_id: your_access_key
      # aws_secret_access_key: your_secret_key