data_engineering_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ./gold_layer_test.duckdb
      schema: gold
      threads: 4
      extensions:
        - httpfs
        - delta
      settings:
        s3_region: us-east-1
        s3_use_ssl: true
        # Configure S3 for writing
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"