data_engineering_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ./gold_layer_test.duckdb
      schema: gold
      threads: 4
      extensions:
        - httpfs
        - delta
        - parquet
      settings:
        s3_region: us-east-1
        s3_use_ssl: true
        s3_access_key_id: "{{ env_var('aws_access_key_id') }}"
        s3_secret_access_key: "{{ env_var('aws_secret_access_key') }}"

      