data_engineering_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ./gold_layer_test.duckdb
      schema: gold
      threads: 4
      extensions:
        - httpfs
        - delta
      