data_engineering_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ./gold_layer_test.duckdb
      schema: gold
      threads: 4
      extensions:
        - httpfs
        - delta
      settings:
        s3_region: us-east-1
        s3_use_ssl: true
        # Configure S3 for writing (optional - uses default AWS credentials if not set)
        aws_profile_name: default