noaa:
  api:
    base_url: "https://www.ncdc.noaa.gov/cdo-web/api/v2"
    endpoints:
      data: "/data"
      datasets: "/datasets"
      datacategories: "/datacategories"
      datatypes: "/datatypes"
      locations: "/locations"
      stations: "/stations"
    rate_limit:
      requests_per_second: 1
      max_retries: 3
      retry_delay_seconds: 1

  data:
    default_dataset: "GHCND"  # Global Historical Climatology Network Daily
    default_datatypes:
      - "TMAX"  # Maximum temperature
      - "TMIN"  # Minimum temperature
      - "PRCP"  # Precipitation
      - "SNOW"  # Snowfall
      - "SNWD"  # Snow depth
    date_format: "yyyy-MM-dd"
    
  kafka:
    topic: "noaa-weather-data"
    consumer_group: "noaa-data-processor"
    
  storage:
    raw_data_path: "data/raw/noaa"
    processed_data_path: "data/processed/noaa"
    checkpoint_location: "data/checkpoints/noaa" 