version: 2

sources:
  - name: weather
    description: "Weather data stored in S3 (silver)"
    tables:
      - name: silver_data
        description: "Date-partitioned weather data"
        meta:
          external_location: "s3://data-eng-bucket-345/silver/weather/**/*.parquet"